### ISSUE TITLE
Should it work with purescript 0.11?

### ISSUE THREAD

**Issue by cideM** [nwolverson/vscode-ide-purescript#46]
After updating purescript to 0.11, VSC complains about `Couldn't find psc-ide-server, check PATH. Looked for: psc-ide-server in PATH: ....` 
I am guessing this has to do with https://github.com/purescript/purescript/issues/2745 ?

**Comment by icyrockcom** [comment]
@cideM More specifically, it has to do with this part of [v0.11.0](https://github.com/purescript/purescript/releases/tag/v0.11.0) changelog:

> The various psc-* executables have been replaced with a single executable called purs.

So for purescript >= 0.11.0 instead of `psc-ide-server` the plugin should run `purs ide server`. 

I had partial success by faking (on Linux):

* Put `psc-ide-server` (including `chmod u+x psc-ide-server`) in `PATH` with this:

```
#!/usr/bin/bash
purs ide server "$@"
```

* Add this to `settings.json`:

```
  "purescript.buildCommand": "pulp build --no-psa -- --json-errors"
```

Unfortunately, the quick hack only goes so far. It brings me to a point where I can edit without "Build error" popups. Markedly, compilation errors are not reported.

**Comment by nwolverson** [comment]
Will be looking at this hopefully today

**Comment by nwolverson** [comment]
This is now released, let me know if any issues.

**Comment by icyrockcom** [comment]
Thanks @nwolverson - just to confirm, at this point it requires adding this:

`  "purescript.useCombinedExe": true`

to `settings.json`, correct? With that added, it's working fine for me, so +1 for a really quick turnaround!

**Comment by nwolverson** [comment]
That's right, if you have a mixture of older/newer projects can stick that in workspace settings. I'll make it the default soon if there are no issues, and it'll get removed at some point later.

(Didn't want to just magic the right answer, as the way of calling the executable is different, and it might not be clear from npm and regular path which one to use.)

**Comment by cideM** [comment]
That was fast, thank you very much :)
